package main //change package name, or delete statement, if desired

// Network generated by DrawFBP

import (
	"github.com/jpaulm/gofbp/components/testrtn"
	"github.com/jpaulm/gofbp/core"
)

type Subnet1 struct {
}

func (subnet *Subnet1) Setup(p *core.Process) {
}

func (subnet *Subnet1) Execute(p *core.Process) {
	net := core.NewSubnet("Subnet1", p)
	write____to_console := net.NewProc("Write____To_Console", &testrtn.WriteToConsNL{})
	subin1 := net.NewProc("SUBIN1", &core.SubInSS{})
	net.Initialize("IN", subin1, "NAME")
	subout2 := net.NewProc("SUBOUT2", &core.SubOutSS{})
	net.Initialize("OUT", subout2, "NAME")
	net.Connect(subin1, "OUT", write____to_console, "IN", 6)
	net.Connect(write____to_console, "OUT", subout2, "IN", 6)
	net.Run()
}
