git push --delete origin v2.0.0
git push --delete origin v2.1.0
git push --delete origin v2.2.0
git push --delete origin v2.2.1
git push --delete origin v2.2.2
git push --delete origin v2.3.0
git push --delete origin v2.4.0
git push --delete origin v2.4.1
git push --delete origin v2.5.0
git push --delete origin v2.6.0