package main //change package name, or delete statement, if desired

// Network generated by DrawFBP

import (
	"github.com/jpaulm/gofbp/components/testrtn"
	"github.com/jpaulm/gofbp/core"
)

func main() {
	params, err := core.LoadXMLParams("params.xml")
	if err != nil {
		panic(err)
	}
	net := core.NewNetwork("Merge")
	net.SetParams(params)
	sender2 := net.NewProc("Sender2", &testrtn.Sender{})
	write___to_console := net.NewProc("Write___To_Console", &testrtn.WriteToConsole{})
	sender1 := net.NewProc("Sender1", &testrtn.Sender{})
	net.Connect(sender1, "OUT", write___to_console, "IN", 6)
	net.Initialize("15", sender1, "COUNT")
	net.Initialize("10", sender2, "COUNT")
	net.Connect(sender2, "OUT", write___to_console, "IN", 6)
	net.Run()
}
