package main //change package name, or delete statement, if desired

// Network generated by DrawFBP

import (
	"github.com/jpaulm/gofbp/components/testrtn"
	"github.com/jpaulm/gofbp/core"
)

func main() {
	net := core.NewNetwork("Subnet-diagram")
	substream___sender := net.NewProc("Substream___Sender", &testrtn.Sender{})
	run___subnet := net.NewProc("Run___Subnet", &Subnet1{})
	write___to_console := net.NewProc("Write___To_Console", &testrtn.WriteToConsole{})
	net.Connect(substream___sender, "OUT", run___subnet, "IN", 6)
	net.Connect(run___subnet, "OUT", write___to_console, "IN", 6)
	net.Initialize("40", substream___sender, "COUNT")
	net.Run()
}
